# Generated by Django 3.0.6 on 2020-06-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['-firstname', '-lastname', '-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['-name', '-firm__name', '-timestamp']},
        ),
    ]
