# Generated by Django 3.0.6 on 2020-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200602_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='district',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='province',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='district',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='province',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
