# Generated by Django 3.0.6 on 2020-06-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200604_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='office',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
